# Generated by Django 2.2 on 2019-09-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_uploadimages_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImages',
        ),
    ]
