# Generated by Django 2.2 on 2019-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190910_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible_home',
            field=models.BooleanField(default=False),
        ),
    ]
